# -*- mode: ruby -*-
# vi: set ft=ruby :
# 2014, s.andres@syseleven.de
#
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "http://uec-images.ubuntu.com/vagrant/trusty/20140531.1/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.ssh.forward_agent = true
  config.vm.define "contrail1" do |contrail1|

    contrail1.vm.hostname = "contrail1"

    #contrail1.vm.synced_folder "/mnt/nfs", "/mnt/nfs"

    config.vm.provision :shell, :path => "install_contrail"
    contrail1.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 4
    end
  end


   config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
   end



end
